Xray License Integration
octopusden/octopus-license-maven-plugin pull request #12
Opened 2024-06-20 05:20 UTC by adellinekania

2024-07-01 08:06 UTC, pgorbachev requested changes

2024-07-01 08:06 UTC, pgorbachev commented on pom.xml
> +                    <artifactId>slf4j-api</artifactId>
If we exclude all slf4j libs then we can use wildcard '*'

2024-07-01 08:06 UTC, pgorbachev commented on src/main/java/org/codehaus/mojo/license/ILicenseProcessor.java
> +public interface ILicenseProcessor {
don't use prefix I for the interfaces

2024-07-01 08:12 UTC, pgorbachev commented on src/main/java/org/codehaus/mojo/license/xray/XrayLicenseProcessor.java
> +            String projectGAV = "gav:%2F%2F" + toString(project);
I think "gav://" is more clear.

2024-07-01 08:15 UTC, pgorbachev commented on src/main/java/org/codehaus/mojo/license/xray/XrayLicenseProcessor.java
> +import java.util.*;
We don't use wildcards in the imports

2024-07-01 08:20 UTC, pgorbachev commented on src/main/java/org/codehaus/mojo/license/xray/XrayLicenseProcessor.java
> +                log.info("Unknown status code for " + toString(project) + " : " + statusCode);
error level

2024-07-01 08:33 UTC, pgorbachev commented
rename nexus.LicenseProcessor to nexus.SonatypeServiceLicenseProcessor

2024-07-01 08:34 UTC, pgorbachev commented
1) introduce flags to disable/enable
a) resolving with Nexus
b) resolving with XRay

2) provide description

2024-07-02 03:29 UTC, adellinekania commented on pom.xml
> +                    <artifactId>slf4j-api</artifactId>
I removed this dependency because artifactory client is not needed anymore

2024-07-02 08:08 UTC, pgorbachev requested changes

2024-07-02 08:08 UTC, pgorbachev commented on src/main/java/org/codehaus/mojo/license/AbstractAddThirdPartyMojo.java
> +    @Parameter( property = "license.useXrayProcessor", defaultValue = "true" )
default = false for XRay

2024-07-02 08:08 UTC, pgorbachev commented on src/main/java/org/codehaus/mojo/license/AbstractAddThirdPartyMojo.java
> +    private Boolean isUseSonatypeProcessor;
default true for Sonatype

2024-07-02 10:11 UTC, pgorbachev approved these changes

2024-07-02 10:35 UTC, fishinitself approved these changes

2024-07-02 13:45 UTC, qu0d approved these changes

2024-07-03 08:03 UTC, merged